# Generated by Django 3.1.7 on 2021-10-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
