# Generated by Django 3.1.7 on 2021-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_manage_app', '0002_auto_20211018_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
